Promote exit tests to API
swiftlang/swift-testing pull request #324
Opened 2024-04-02 17:52 UTC by grynspan

This PR promotes exit tests to API, pending approval of the proposal at https://github.com/swiftlang/swift-evolution/pull/2718.

View the full proposal [here](https://github.com/grynspan/swift-evolution/blob/jgrynspan/swift-testing-exit-tests/proposals/testing/NNNN-exit-tests.md).

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

2024-04-12 14:24 UTC, stmontgomery commented on Documentation/Proposals/NNNN-exit-tests.md
> +> tests" to refer to them.
"Termination tests" is another term I have heard for this concept which may be worth mentioning

2024-07-12 15:43 UTC, grynspan commented
Rebased.

2024-08-15 23:13 UTC, grynspan commented
Rebased on #615.

2024-09-24 18:28 UTC, dabrahams commented
Nice.  Three notes:

1. You can probably support exit tests on platforms that don't let you spawn, because there is always(?) a test driver program running on a host system like a Mac.  I outlined how this could work for googletest and CMake [here](https://github.com/google/googletest/issues/4595): instead of looping over all the tests in a process on the target platform, you loop over the expected-to-fail ones on the host and launch a separate target process for each one.
2. I'm not familiar enough with what you're doing to know whether you've covered this case already, but it's sometimes important to be able to verify stdout/stderr contents in addition to detecting abnormal exit.  I hope your design allows that.
3. With GTest I found it very inconvenient that platforms weren't uniform w.r.t. what I could detect in an exit test.  I had to make uniformity macros that allowed me to write one test for all platforms and verify as much as possible.  They are described (and linked) [here](https://github.com/google/googletest/issues/4600).  A better library would provide these facilities OOTB.

2024-09-24 18:32 UTC, grynspan commented
@dabrahams Please read the draft pitch. :) 1. and 2. are covered in it. It sounds like 3. is sufficiently covered I think? `.signal()` is not supported on Windows because Windows itself only has emulated signal support. I know how we can fix that (by replacing the default signal handlers on Windows that call `exit(3)` with something that communicates across the "back channel") but I've punted that from the initial proposal for the sake of complexity.

2024-09-24 18:40 UTC, dabrahams commented
I skimmed the pitch; I didn't see coverage for 1; what I saw was

> The need for exit tests on other platforms is just as strong as it is on the supported platforms (macOS, Linux, and Windows). These platforms do not support spawning new processes, so a different mechanism for running exit tests **would** be needed.

emphasis mine.  I read that as meaning “we don't have an answer for these platforms.”

What I see about 2) is an explicit statement that it isn't supported.

It sounds like 3 is not sufficiently covered, since the Windows signal detection case is one of the ones for which I had to build a workaround manually, and you say you're punting it 'till later.

Maybe by “covered” you just mean “discussed.” In that case I don't see much discussion of strategies for handling these things, so I thought my comment would be useful.  If it wasn't, feel free to ignore it.

2024-09-24 18:49 UTC, grynspan commented
> I skimmed the pitch; I didn't see coverage for 1; what I saw was
> 
> > The need for exit tests on other platforms is just as strong as it is on the supported platforms (macOS, Linux, and Windows). These platforms do not support spawning new processes, so a different mechanism for running exit tests **would** be needed.
> 
> emphasis mine. I read that as meaning “we don't have an answer for these platforms.”

I'm sure that, as a former Apple employee, you can appreciate that my ability to discuss iOS _et al._ is limited. 🙂

> What I see about 2) is an explicit statement that it isn't supported.

It's listed as a future direction. That doesn't mean it can't be done, just that it's not part of this pitch.

> It sounds like 3 is not sufficiently covered, since the Windows signal detection case is one of the ones for which I had to build a workaround manually, and you say you're punting it 'till later.

If you want to detect _specifically_ that a Windows process terminated with a _specific signal_, that's something that needs additional work beyond the scope of this pitch. If you want to detect that a Windows process terminated abnormally, which would include termination due to an unhandled signal, that's supported and covered by the general `.failure` exit condition.

2024-09-24 18:52 UTC, grynspan commented
To be clear (I'm now reading my initial reply as snarky, which wasn't intentional), I appreciate the feedback @dabrahams. I can certainly amend the pitch to make it clearer we're thinking about these things.

2024-10-22 02:01 UTC, grynspan commented
Windows signals are now handled! #766

2024-10-22 02:03 UTC, grynspan commented
And stdout/stderr will be soon too. #773

2024-10-22 02:20 UTC, dabrahams commented
> Windows signals are now handled! https://github.com/swiftlang/swift-testing/pull/766

Nice; That puts you at least one step ahead of googletest, IIRC.

2025-01-06 08:05 UTC, maartene commented
Is there any news on this PR?

2025-01-06 14:12 UTC, grynspan commented
I'm still actively maintaining this branch/PR. We are not planning to formally propose this feature until the testing workgroup is set up, at the earliest.

2025-02-24 21:48 UTC, grynspan commented
@swift-ci test

2025-02-28 21:02 UTC, grynspan commented
@swift-ci test

2025-03-03 20:51 UTC, amartini51 commented on Documentation/Proposals/NNNN-exit-tests.md
> +/// }
Either indent or use backticks around this code listing, otherwise it will render as a paragraph.

2025-03-03 20:51 UTC, amartini51 commented on Documentation/Proposals/NNNN-exit-tests.md
> +/// }
Either indent or use backticks around this code listing, otherwise it will render as a paragraph.

2025-03-03 21:13 UTC, grynspan commented on Documentation/Proposals/NNNN-exit-tests.md
> +/// }
This is a code block inside a code block. It doesn't need to be rendered.

2025-03-03 21:13 UTC, grynspan commented on Documentation/Proposals/NNNN-exit-tests.md
> +/// }
This is a code block inside a code block. It doesn't need to be rendered.

2025-03-03 21:13 UTC, grynspan commented on Documentation/Proposals/NNNN-exit-tests.md
> +/// }
This is a code block inside a code block. It doesn't need to be rendered.

2025-03-03 22:08 UTC, grynspan commented
@swift-ci test

2025-03-03 22:19 UTC, grynspan commented
@swift-ci test

2025-03-24 19:54 UTC, grynspan commented
@swift-ci test

2025-03-25 15:02 UTC, grynspan commented
@swift-ci test

2025-03-25 17:56 UTC, grynspan commented
@swift-ci test

2025-03-25 18:36 UTC, grynspan commented
@swift-ci test

2025-03-25 20:13 UTC, grynspan commented
@swift-ci test

2025-03-26 12:05 UTC, iamleeg requested changes
Thanks for writing this article, it's really helpful for developers!

2025-03-26 12:05 UTC, iamleeg commented on Sources/Testing/Testing.docc/exit-testing.md
> +### Constraints on exit tests
```suggestion
### Write exit tests within constraints
```
…or something else that tells the developer what to do.

2025-03-26 12:05 UTC, iamleeg commented on Sources/Testing/Testing.docc/exit-testing.md
> +#### State cannot be captured
```suggestion
#### Don't capture state in the test body
```

2025-03-26 12:05 UTC, iamleeg commented on Sources/Testing/Testing.docc/exit-testing.md
> +Exit tests cannot capture any state originating in the parent process or from
```suggestion
Exit tests can't capture any state originating in the parent process or from
```

2025-03-26 12:05 UTC, iamleeg commented on Sources/Testing/Testing.docc/exit-testing.md
> +the enclosing lexical context. For example, the following exit test will fail to
```suggestion
the enclosing lexical context. For example, the following exit test fails to
```

2025-03-26 12:05 UTC, iamleeg commented on Sources/Testing/Testing.docc/exit-testing.md
> +#### Exit tests cannot be nested
```suggestion
#### Don't nest exit tests
```

2025-03-26 12:05 UTC, iamleeg commented on Sources/Testing/Testing.docc/exit-testing.md
> +An exit test cannot run within another exit test.
```suggestion
An exit test can't run another exit test.
```

It means the same to say "a test can't run a child test" as "a test can't run in a parent test", and it's simpler.

2025-03-26 12:08 UTC, grynspan commented on Sources/Testing/ExitTests/ExitTest.Condition.swift
>    /// the process is yielded to the parent process. Linux and other POSIX-like
"Reported" may be better. The mechanism that gets this value into the parent process involves the kernel, so the terminology is more vague than usual.

2025-03-26 12:11 UTC, grynspan commented on Sources/Testing/Testing.docc/OrganizingTests.md
> +#### Test suite types must always be available
I think you actually wrote this one! It's an unrelated article; I just fixed the nesting depth.

2025-03-26 12:11 UTC, grynspan commented on Sources/Testing/Testing.docc/OrganizingTests.md
>  Although `@available` can be applied to a test function to limit its
Unrelated article—we can review it in a separate PR.

2025-03-26 12:14 UTC, grynspan commented on Sources/Testing/Testing.docc/exit-testing.md
> +child process.
They should assume nothing is inherited. The set of open file descriptors is platform-dependent but we try to close as many as we can. And, due to the nature of process spawning via POSIX API, the environment is inherited but may not exactly match that of the parent.

2025-03-26 12:15 UTC, grynspan commented on Sources/Testing/Testing.docc/exit-testing.md
> +the process exits naturally. If an error is thrown from the body, it is handled
"Don't know" and "nothing".

2025-03-26 12:17 UTC, grynspan commented on Sources/Testing/Testing.docc/exit-testing.md
> +#### State cannot be captured
This isn't an instruction. It's physically impossible to do it. There is no "do".

2025-03-26 12:17 UTC, grynspan commented on Sources/Testing/Testing.docc/exit-testing.md
> +#### Exit tests cannot be nested
This isn't an instruction. It's physically impossible to do it. There is no "do".

2025-03-26 12:18 UTC, grynspan commented on Sources/Testing/Testing.docc/exit-testing.md
> +### Constraints on exit tests
This section doesn't tell the developer what to do. It is enumerating constraints on the code they write.

2025-03-26 13:12 UTC, grynspan commented on Sources/Testing/ExitTests/ExitTest.Result.swift
>      /// exit status reported by the process that hosted the exit test.
This para is redundant if I rewrite the summary anyway.

2025-03-26 13:25 UTC, grynspan commented on Sources/Testing/Testing.docc/exit-testing.md
> +as if the error were thrown from `main()` and the process is forced to exit.
Within the exit test, the developer can write more or less any valid Swift code. Installing uncaught exception handlers is not a Swift concept (but we don't actively block it.) Same with signal handlers—if you install your own, you're out of the realm of Swift and we make no guarantees (but it's not UB _per se_.)

`atexit()`/`std::terminate()` behave the same way they would in any other process and I don't know if they're worth calling out.

2025-03-26 13:45 UTC, grynspan commented on Sources/Testing/Testing.docc/exit-testing.md
> +#### State cannot be captured
Refactored this section and moved it up.

2025-03-26 13:53 UTC, grynspan commented on Sources/Testing/Testing.docc/exit-testing.md
> +  third-party dependencies you have declared in your package.
Also added "or Xcode project" here.

2025-03-26 13:53 UTC, grynspan commented on Sources/Testing/Testing.docc/exit-testing.md
> +Your code may contain calls to [`precondition()`](https://developer.apple.com/documentation/swift/precondition(_:_:file:line:)),
I'm having trouble building this out in a way that doesn't feel contrived ("you might write code that crashes, maybe you want to test that code yes?")

Could use some brainstorming here.

2025-03-26 14:47 UTC, iamleeg approved these changes
Thanks, @grynspan!

2025-03-26 14:55 UTC, iamleeg commented on Sources/Testing/Testing.docc/exit-testing.md
> +Your code may contain calls to [`precondition()`](https://developer.apple.com/documentation/swift/precondition(_:_:file:line:)),
"Crashes" sounds like an unexpected end. So you wouldn't want an exit test, in that case; you'd want a regular test that expects your code to run to completion, and fails if the code crashes.

2025-03-26 14:56 UTC, iamleeg commented on Sources/Testing/Testing.docc/exit-testing.md
> +child process.
Is there value in listing that out for developers?

2025-03-26 22:44 UTC, grynspan commented
@swift-ci test

2025-03-27 01:46 UTC, grynspan commented on Sources/Testing/Testing.docc/exit-testing.md
> +as if the error were thrown from `main()` and the process is forced to exit.
Exit handlers will still run if they are set in the child process and if the nature of the process exit would normally allow for it.

2025-03-27 15:14 UTC, grynspan commented on Sources/Testing/Testing.docc/exit-testing.md
> +Your code may contain calls to [`precondition()`](https://developer.apple.com/documentation/swift/precondition(_:_:file:line:)),
I'm going to leave the overview as-is for the moment—let's still plan to revise it before Swift 6.2 ships.

2025-04-01 18:07 UTC, grynspan commented
@swift-ci test

2025-04-06 22:55 UTC, grynspan commented
@swift-ci test

2025-04-15 17:40 UTC, grynspan commented
@swift-ci test

2025-04-29 15:17 UTC, grynspan commented
@swift-ci test

2025-04-30 21:13 UTC, stmontgomery commented on Sources/Testing/ExitTests/ExitTest.Condition.swift
> +  public init(_ exitStatus: ExitStatus) {
I notice this `init` for `ExitTest.Condition` doesn't have any DocC symbol documentation. Often for "trivial" initializers we omit this, but since it's a `public` API, it looks somewhat sparse in our rendered documentation, and it seems like we at least usually have docs for all _public_ initializers. I'll add some basic documentation for this.

2025-04-30 21:41 UTC, stmontgomery commented on Sources/Testing/ExitTests/ExitTest.Condition.swift
> +  /// ## Topics
Related to [this comment](https://github.com/swiftlang/swift-testing/pull/324/files#r2069450546), I noticed while reviewing the rendered docs that `init(_:)` is not included in this Topics list and it's getting implicitly added at the bottom in an "Initializers" section. I suppose that's not a problem, but wanted to point it out.

2025-04-30 21:45 UTC, grynspan commented on Sources/Testing/ExitTests/ExitTest.Condition.swift
> +  public init(_ exitStatus: ExitStatus) {
Go for it!

2025-04-30 21:49 UTC, stmontgomery commented on Sources/Testing/Expectations/Expectation+Macro.swift
> -/// An exit test cannot run within another exit test.
I see most of the content removed here has been adapted in the `<doc:exit-testing>` article, but I don't see a reference to this sentence

> An exit test cannot run within another exit test.

2025-04-30 21:58 UTC, stmontgomery commented
@swift-ci please test

2025-04-30 22:09 UTC, stmontgomery approved these changes

2025-04-30 22:22 UTC, grynspan commented on Sources/Testing/Expectations/Expectation+Macro.swift
> -/// An exit test cannot run within another exit test.
Might have gotten elided during editing. It isn't worth its own section, but maybe put it as a `- Note` callout somewhere reasonable?

2025-04-30 23:18 UTC, grynspan commented on Sources/Testing/ExitTests/ExitTest.Condition.swift
> +  /// Initialize an instance of this type that matches the specified exit
@iamleeg Please review this symbol's blurb. Thanks! This is a casting initializer.

2025-05-01 08:30 UTC, iamleeg approved these changes
Looks good to me, now!

2025-05-01 08:30 UTC, iamleeg commented on Sources/Testing/ExitTests/ExitTest.Condition.swift
> +  /// Initialize an instance of this type that matches the specified exit
This looks great, thank you!

2025-05-01 15:30 UTC, stmontgomery commented
@swift-ci please test

2025-05-01 15:45 UTC, stmontgomery commented
The macOS CI failure is expected to be resolved by https://github.com/swiftlang/swift/pull/80830, but the release of a new main snapshot toolchain is currently blocked for unrelated reasons.

2025-05-01 15:56 UTC, merged