Add curation for the Trait protocol.
swiftlang/swift-testing pull request #345
Opened 2024-04-11 22:10 UTC by medreisbach

Add curation for the Trait protocol.

Part 4 of changes for rdar://119702877

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

2024-04-18 22:18 UTC, chuckdude approved these changes
This looks great! Thanks, Matt.

2024-04-19 13:16 UTC, grynspan approved these changes
Looks good, just one question (not a blocker for merging.)

2024-04-19 13:16 UTC, grynspan commented on Sources/Testing/Testing.docc/Traits/Trait.md
> +- ``Trait/comment(_:)``
Should we move the `comments` property here?

2024-04-19 13:16 UTC, grynspan commented on Sources/Testing/Testing.docc/Traits/Trait.md
> +### Associating issues
Use "bugs" here. An "issue" in swift-testing's DSL is an instance of `Issue`.

2024-04-19 13:17 UTC, grynspan requested changes
Sorry, just noticed one thing that needs correcting. :(

2024-04-19 19:32 UTC, grynspan commented on Sources/Testing/Testing.docc/Traits/Trait.md
> +- ``Trait/comments``
I meant the property _and_ the factory function, sorry!

2024-04-19 19:38 UTC, grynspan commented on Sources/Testing/Testing.docc/Traits/Trait.md
> +- ``Trait/comments``
Actually let's just switch it back to the function—I think we need to think about the corresponding properties for _all_ of these traits. Sorry for the noise.

2024-04-22 19:52 UTC, grynspan commented on Sources/Testing/Testing.docc/Traits/Trait.md
> +- ``Trait/comments``
Yeah ignore me here. I think I confused myself.

2024-04-22 19:52 UTC, grynspan approved these changes

2024-04-22 19:53 UTC, merged