[android] fix the build
swiftlang/swift-testing pull request #681
Opened 2024-09-11 18:48 UTC by hyp

the posix_filesystem module is available only from Swift, as it comes from the Swift android overlay.

### Motivation:

Fixing the android build.

### Modifications:

Modify include.

### Result:

It builds.

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

2024-09-11 18:48 UTC, hyp commented
@swift-ci please test

2024-09-11 18:50 UTC, compnerd approved these changes

2024-09-11 18:51 UTC, stmontgomery approved these changes

2024-09-11 19:07 UTC, grynspan commented on Sources/_TestingInternals/include/Includes.h
> +#ifdef __swift__
```suggestion
#if defined(__swift__)
```

2024-09-11 19:08 UTC, grynspan commented on Sources/_TestingInternals/include/Includes.h
> +#else
We don't need this `#else` clause.

2024-09-11 19:08 UTC, grynspan requested changes
Nitpicks.

2024-09-11 19:36 UTC, hyp commented
@swift-ci please test

2024-09-11 20:01 UTC, grynspan approved these changes

2024-09-11 20:35 UTC, merged

2024-09-12 15:29 UTC, grynspan commented
@hyp Note if you need this fix in Swift 6.0.1, please clone the PR and nominate it using the procedure outlined [here](https://forums.swift.org/t/swift-6-0-release-process/70220).